# Generated by Django 5.2.7 on 2025-11-01 07:28

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articlecolumn_articlepost_column'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
